### ISSUE TITLE
Bumping against C stack limit?

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#15]
I get this error:

    Output created: 03-data-manip-basics.html
    Error: C stack usage  8678916 is too close to the limit
    Execution halted

when I try to run the tutorial below

    ---
    title: "Data Manipulation Basics"
    output: tutor::tutorial
    runtime: shiny_prerendered
    ---
    
    ```{r setup, include=FALSE}
    library(tidyverse)
    library(nycflights13)
    ```
    
    what's going on?

    ```{r}
    flights
    ```

I'm not sure what is happening, but I can avoid the error it in two ways. If I do either of these things, the tutorial runs without error:

1) (sensibly) show only the head of `flights` (but notice that flights is a tibble, so it displays concisely anyhow)

        ---
        title: "Data Manipulation Basics"
        output: tutor::tutorial
        runtime: shiny_prerendered
        ---
        
        ```{r setup, include=FALSE}
        library(tidyverse)
        library(nycflights13)
        ```
        
        what's going on?
    
        ```{r}
        head(flights)
        ```

2) Remove the `'` in the line before the last code chunk:

        ---
        title: "Data Manipulation Basics"
        output: tutor::tutorial
        runtime: shiny_prerendered
        ---
        
        ```{r setup, include=FALSE}
        library(tidyverse)
        library(nycflights13)
        ```
    
        whats going on?

        ```{r}
        flights
        ```

**Comment by jjallaire** [comment]
Thanks for the easy repro case. Fixed within rmarkdown
