### ISSUE TITLE
Improve padding when topic index scrolls

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tutor#21]
I think we need a bit more left padding for the body. I also think it would be nice if the scroll-bar had better extension all the way to the top (it's not the end of the world, but the scrollbar ending short of the top creates a border effect which is odd because there is no other visual signs of a border).

<img width="1029" alt="screen shot 2017-03-01 at 3 40 27 pm" src="https://cloud.githubusercontent.com/assets/104391/23480367/aebfabbe-fe95-11e6-9a6b-07fc5c1671f2.png">

@robbyshaver

**Comment by robbyshaver** [comment]
Good  catch - I have scroll bars set to only appear when scrolling so I didn't see this. Fixed.
