### ISSUE TITLE
New format should make use of author and date metadata

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tutor#22]
Probably should go below the title.

<img width="1286" alt="screen shot 2017-03-01 at 3 48 44 pm" src="https://cloud.githubusercontent.com/assets/104391/23480647/adf2c40e-fe96-11e6-85ab-db62d6959ae6.png">

@robbyshaver

**Comment by robbyshaver** [comment]
Fixed this by moving the doc-metadata block into the sidebar, so we should pick up all the possible meta data.
