### ISSUE TITLE
allow-skip and progressive attributes need to have data prefix

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tutor#23]
We want our HTML to be valid HTML5 so as a result we preface attributes with `data-`. Here are the two cases where we are using attributes without the prefix (`progressive` and `allow-skip`):

https://github.com/rstudio/tutor/blob/feature/new-tutorial-format/inst/rmarkdown/templates/tutorial/resources/tutorial-format.js#L145

https://github.com/rstudio/tutor/blob/feature/new-tutorial-format/inst/rmarkdown/templates/tutorial/resources/tutorial-format.js#L179

@robbyshaver

**Comment by robbyshaver** [comment]
I didn't realize the data prefix was mandatory - oops - fixed.
