### ISSUE TITLE
TOC does not appear for sections that occur before the first exercise

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#24]
The table of contents does not appear for a tutorial until you navigate to the first section that has an exercise. You can see the effect in the demo document below:

    ---
    title: "Demo Tutorial"
    output: tutor::tutorial
    runtime: shiny_prerendered
    ---
    
    ```{r setup, include=FALSE}
    library(tutor)
    ```
    
    ## Welcome
    
    This is the Welcome section
    
    ## First task
    
    This is the First Task section
    
    ## Second Task
    
    This is the Second Task section
    
    ```{r one, exercise = TRUE}
    
    ```

It prints like this the first time through:

<img width="1212" alt="screen shot 2017-03-03 at 2 20 20 pm" src="https://cloud.githubusercontent.com/assets/85014/23565760/eca91f18-001c-11e7-9b13-6f92e16b1c62.png">

<img width="1212" alt="screen shot 2017-03-03 at 2 20 23 pm" src="https://cloud.githubusercontent.com/assets/85014/23565774/f48329ae-001c-11e7-8069-d4074efa1fca.png">

<img width="1212" alt="screen shot 2017-03-03 at 2 20 25 pm" src="https://cloud.githubusercontent.com/assets/85014/23565777/f8cf9f7e-001c-11e7-948c-d346aa73ae9f.png">

**Comment by robbyshaver** [comment]
This was caused by a failure to redraw bug in the IDE browser - added a css work around that appears to have fixed it.
