### ISSUE TITLE
Progressive reveal does not provide a cue that a hidden section follows.

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#26]
When progressive reveal is on, there is no indication to the reader that a tutorial contains hidden sections to unlock. For example, there is a hidden section waiting to be revealed here (code below):

<img width="1212" alt="screen shot 2017-03-03 at 2 48 17 pm" src="https://cloud.githubusercontent.com/assets/85014/23566567/76a363ba-0020-11e7-982a-5a57e34fd020.png">

A user can miss the hidden sub-section by using the TOC to navigate past them. Related to #25 because a user will always miss sub-sections if the current sub-section does not contain an exercise (the method for revealing sub-sections). They will also miss hidden sections when they choose not to do an exercise.

Both issues can be resolved by separating progressive reveal from exercise completion and tying it to a "Go On" button that appears whenever a hidden section follows.

````
---
title: "Demo Tutorial"
output: 
  tutor::tutorial:
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
checker <- function(label, user_code, check_code, envir_result, evaluate_result, ...) {
  list(message = "Good Job!", correct = TRUE, location = "append")
}
tutor_options(exercise.checker = checker)
```

## Welcome

### Visible sub-section

This sub-section is visible. It contains a boring exercise that you choose not to do. Notice that there is no "Next Topic" button.

```{r one, exercise = TRUE}

```

```{r one-check}
"foo"
```

### Hidden sub-section

This sub-section is hidden. You do not know that it exists.

## Second Task

Once "finished" above, you can navigate here with the TOC.
````

**Comment by robbyshaver** [comment]
This feature already exists, but you control whether or not it's enabled.  See the doc for exercise skipping here for how to turn it on / off:

https://rstudio.github.io/tutor/formats.html#exercise_skipping

**Comment by garrettgman** [comment]
It seems like a very bad idea to make the above ambiguity possible--but that said, the problem remains and this issue should be reopened. 

If an author does not want to let their students skip exercises and also has a sub-section without an exercise, the sub-sections beyond it will remain hidden and inaccessible:

````
---
title: "Demo Tutorial"
output: 
  tutor::tutorial:
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
```

## Welcome

### Visible sub-section

This sub-section is visible. But it does not have an. Notice that there is no "Next Topic" button.

### Hidden sub-section

This sub-section is hidden. You do not know that it exists.

## Second Task

Once "finished" above, you can navigate here with the TOC.
````

<img width="1212" alt="screen shot 2017-03-06 at 5 34 31 pm" src="https://cloud.githubusercontent.com/assets/85014/23633293/35c32d74-0293-11e7-829c-279936f96ed6.png">


If the author does allow skipping. The hidden sub-sections will be cued with a button that says "Skip" (it should say "Go On"). And this button does not reveal the section when students click on it.

````
---
title: "Demo Tutorial"
output: 
  tutor::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
```

## Welcome

### Visible sub-section

This sub-section is visible. But it does not have an. The skip button does not seem to work when clicked.

### Hidden sub-section

This sub-section is hidden. You do not know that it exists.

## Second Task

Once "finished" above, you can navigate here with the TOC.
````

<img width="1212" alt="screen shot 2017-03-06 at 5 35 25 pm" src="https://cloud.githubusercontent.com/assets/85014/23633336/5b310720-0293-11e7-8792-5533e19d4c03.png">
