### ISSUE TITLE
Puzzling C stack usage error

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#31]
I'm getting a puzzling C stack usage error when I combine an exercise that calls `nycflights13::flights` with an html formatted exercise hint. As in the document below.
````
---
title: "Data basics - Error"
output: tutor::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
library(tidyverse)
library(nycflights13)
```
 
```{r flights2, exercise = TRUE, exercise.eval = TRUE}
flights
``` 

<div id="flights2-hint">
**Hint:** Type the name of the data frame that you want to print and then click the blue button. I've already loaded the nycflight13 package for you.
</div>
````
<img width="880" alt="screen shot 2017-03-06 at 4 37 35 pm" src="https://cloud.githubusercontent.com/assets/85014/23631384/48e98ad0-028c-11e7-9c5c-8a9b9dd9fa7f.png">

If I remove the hint, or transform it into a knitr hint (like below), the error disappears.

````
---
title: "Data basics"
output: tutor::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
library(tidyverse)
library(nycflights13)
```
 
```{r flights2, exercise = TRUE, exercise.eval = TRUE}
flights
``` 

```{r flights2-hint}
"**Hint:** Type the name of the data frame that you want to print and then click the blue button. I've already loaded the nycflight13 package for you."
```
````

This is a minimal example trimmed down from a real tutorial where the hint applied to a different exercise (not the one that calls nycflights13::flights). 

The exercises above *always* return the C stack usage error -- even without a hint -- if you remove the `library(tidyverse)` call (in which case `flights` does not print as a concise tibble, but as a very large data set).

HTML formatted hints seem to work generally, I've only received this error in combination with `flights`, which is an example data set used throughout _R for Data Science_ and the tutorials.

**Comment by jjallaire** [comment]
This should be fixed in the development version of rmarkdown. Try installing that and see if the error still occurs.

Do you think that the default data frame display should be "tibble" rather than "paged"? Even if we solve the C stack issue people will still end up creating arbitrarily large html files when they print large data frames.

**Comment by jjallaire** [comment]
Going to close this since I can't repro with the development version of rmarkdown. Feel free to re-open if you are still seeing the error.

**Comment by garrettgman** [comment]
Thanks @jjallaire, it works for me with the devel version. I think users may find tibbles an annoyance if they do not ask for them.

**Comment by jjallaire** [comment]
So do you prefer the paged tables or just a plain R data frame printout?

Maybe if we used paged tables we could set a limit on how many rows can be included. @javierluraschi is there a way to do this?

**Comment by garrettgman** [comment]
I prefer the paged tables over the R data frame printout.

**Comment by mine-cetinkaya-rundel** [comment]
I agree with @garrettgman on paged tables

**Comment by javierluraschi** [comment]
Yes, we can limit the number rows/columns included using `max.print` and `cols.max.print`; to control the visible number of rows/columns we use `rows.print` and `cols.print`.
