### ISSUE TITLE
Rename the Skip button to "Go On"

### ISSUE THREAD

**Issue by robbyshaver** [rstudio/tutor#34]
Garrett suggests that this would be clearer for progressive reveal.

**Comment by garrettgman** [comment]
Here is my reason:

To avoid confusion, each hidden section should be replaced by:

1. A visual object that alerts the reader that there is a hidden section
2. A self-explanatory control for accessing the hidden section.

A "Go On" button does both of these things. (A "Skip" button doesn't make sense if the visible section contains only text --- a student should read that text! "Skip" also conflates exercise completion with progressive reveal. See #35)

**Comment by robbyshaver** [comment]
Renamed the button to "Continue" (along with change the overall progressive behavior).
