### ISSUE TITLE
Pressing Next Topic button for a topic with no sections should update the progress bar

### ISSUE THREAD

**Issue by robbyshaver** [rstudio/tutor#36]
Currently, nothing happens. The progress bar should update to show the topic as complete.

**Comment by garrettgman** [comment]
Could you extend this so the "Next Topic" button always acts as the "Continue" button for the last sub-section? For example, here you end the first topic by clicking "Continue" to reveal a "Next Topic" button. It seems like we could collapse the last Continue + Next Topic sequence.

````
---
title: "Continue to the Next Topic button"
output: 
  tutor::tutorial:
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
```

## Topic 1

### Sub-section 1

A sub-section.

### Sub-section 2

A second sub-section

### Sub section 3

A third sub-section. Click through two buttons to advance.

## Topic 2

```{r foo, exercise = TRUE}

```
````

**Comment by robbyshaver** [comment]
Yeah, that occurred to me too. Could you post that as a separate issue please? It's not really related to this one, which is about handling topics with no sections.

**Comment by garrettgman** [comment]
Certainly. Posted at #39.
