### ISSUE TITLE
consider using tibbles or at least limiting the number of rows for paged tables

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tutor#38]

**Comment by jjallaire** [comment]
It looks like the number of rows included in a paged table can be limited using the `max.print` chunk option. Currently this defaults to 10,000 (based on the R option of the same name) which is why we were getting such a huge JSON payload in your example. 

In this commit (https://github.com/rstudio/tutor/commit/54fc97f28067d575383bab311733b3b1f62b04e7) I've changed the default within `tutor::tutorial` to 1,000 and restored the use of paged tables as the default rendering method. You can always override this at the document or chunk level by specifying an alternate `max.print` chunk option.

**Comment by garrettgman** [comment]
Is there a way to force an exercise chunk to show the default R print method for data frames? (to help teach why and how to use `as_tibble()`)?

**Comment by jjallaire** [comment]
I think that for that tutorial you could just set df_print = "default" and
then you'll get the default behavior (right now you can only set df_print
globally not per-chunk)

**Comment by garrettgman** [comment]
Excellent! Thanks. I did not know about df_print.
