### ISSUE TITLE
Use Next Topic button as the Continue button for the last sub-section in a topic.

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#39]
When progressive reveal is set to true, the last sub-section of a topic ends up with a continue button that when pressed reveals a Next Topic button (demo's below). Can we combine the two buttons for the last sub-section in a topic?

````
---
title: "Continue to the Next Topic button"
output: 
  tutor::tutorial:
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
```

## Topic 1

### Sub-section 1

A sub-section.

### Sub-section 2

A second sub-section

### Sub section 3

A third sub-section. Click through two buttons to advance.

## Topic 2

```{r foo, exercise = TRUE}

```
````

**Comment by robbyshaver** [comment]
It was much simpler to implement, and I think a simpler user experience, to make clicking the Continue button for the last section in a topic advance you to the next topic.

**Comment by garrettgman** [comment]
Sounds good to me :) Is this closed then?
