### ISSUE TITLE
File names can't start with non-alpha

### ISSUE THREAD

**Issue by dtkaplan** [rstudio/tutor#4]
A tutor Rmd file whose name begins with a non-alphabetic character, e.g. `05-collection.Rmd`, will run only if there are no graphics chunks in the document. This behavior is inherited from `shiny::add_resource_path`. Files without graphics chunks work find, even with names starting with a numeral.

The obvious quick fix is not to start tutor Rmd file names with a non-alphabetic character.  (This is a moral conflict with the naming style encouraged by `bookdown`, but not a technical conflict.) Still, the start-with-alphabetical-character-if-graphics-chunk is perhaps unnecessarily obscure.

**Comment by wch** [comment]
@jjallaire I don't know of any technical reason why it requires a non-numeric first character -- perhaps @jcheng5 knows?

**Comment by jcheng5** [comment]
I don't think there's a good reason. I can only imagine I used typical variable name rules. Feel free to PR

**Comment by jjallaire** [comment]
PR here: https://github.com/rstudio/shiny/pull/1529
