### ISSUE TITLE
Difficult to distinguish paragraphs in rstudio-tutor.css

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#40]
The rstudio-tutor.css style file uses the same line spacing between paragraphs and lines, which makes multiple paragraphs look like a single chunk of text with ragged edges:

<img width="1212" alt="screen shot 2017-03-09 at 4 55 18 pm" src="https://cloud.githubusercontent.com/assets/85014/23772639/b855c3b6-04e9-11e7-804c-7bba91c45f0e.png">

**Comment by jjallaire** [comment]
On a related note, I appreciate providing a bit of extra line leading for
readability but I think maybe we should bring it in a bit, as the current
spacing seems a bit too much (it looks like a double-spaced printed
document to me, maybe go for 1 1/2 spaced?)
