### ISSUE TITLE
Start Over confirmation dialog

### ISSUE THREAD

**Issue by m--** [rstudio/tutor#42]
Start Over uses a `window.confirm` dialog box. Could we do this with a JavaScript modal dialog instead? It'd be great if we could give it consistent styling and control the text a bit more. Additionally, if you click "Prevent this page from creating additional dialogs", the Start Over functionality no longer works (not surprising, but not exactly what we want, either). Here's what it looks like in RStudio.cloud right now:

![start_over](https://cloud.githubusercontent.com/assets/618347/24011888/4e53edda-0a39-11e7-838f-c12b57f256be.png)

**Comment by jjallaire** [comment]
Good catch. Yes, I'll make that change before our CRAN release.

**Comment by robbyshaver** [comment]
Note that there's another system dialog, called from tutor-format.js

window.alert("You must complete the " + exs + " in this section before continuing.");

It would be nice to fix this one also.

**Comment by jjallaire** [comment]
See also #43 for pending refinements
