### ISSUE TITLE
Skip section instead of (or in addition to) skip exercise

### ISSUE THREAD

**Issue by robbyshaver** [rstudio/tutor#44]
The current tutor api includes a method: skipExercise() and fires an event: progressEvent.event === "exercise_skipped".  However, the UI actually allows the user to skip sections, not exercises.

The code in tutorial-format.js works around this, but it's kind of a hack. It passes in the id of a section to skipExercise, and in the handler for the "exercise_skipped" event, fishes the id from the empty jquery object like so:

  function exerciseSkipped(exerciseElement) {
    var sectionSkippedLabel;
    if (exerciseElement.length) {
      console.log('something changed in tutor ...');
      return;
    //  sectionSkippedLabel = exerciseElement.attr('data-label');
    }
    else {  // fish out the id of the section that got skipped
      sectionSkippedLabel = $(exerciseElement).selector.split('"')[1];
    }

It would be much cleaner if we had a skipSection method and a "section_skipped" event to work with - particularly if somebody looks at tutorial-format.js and tries to figure out what's going on.

**Comment by jjallaire** [comment]
So it seems like if I just remove `exercise_skipped` entirely and replaced it with `section_skipped` that would both better conform to what the UI actually allows and enable you to clean up the dirty hack. Is that correct?

**Comment by robbyshaver** [comment]
Yep, that's right.
