### ISSUE TITLE
ensure that docs on progressive reveal and skipping reflect latest behavior

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tutor#45]
@garrettgman I know that you and @robbyshaver iterated on the behavior of progressive display and skipping quite a bit after I wrote these initial docs:

https://rstudio.github.io/tutor/formats.html#progressive_reveal

Could you make any revisions to these documents which you believe are required? (Note that there is a separate 'docs' RStudio project within the docs subdirectory of the repo which you can use to edit/rebuild the docs website.

**Comment by garrettgman** [comment]
Fixed by 7a5f5ed81ed62fc59959b2b9f35090a661dab1db
