### ISSUE TITLE
promote a set of example tutorials within the documentation

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tutor#46]
I'd like to promote a set of 4-6 example tutorials within the documentation (really just a link to the running tutorial and it's source code). @garrettgman Could you let me know which tutorials you think would be the best examples and provide links to them / their source code? Once you do this I'll add an "Examples" tab to the documentation website.

**Comment by garrettgman** [comment]
@jjallaire I recommend these five tutorials:

https://tutorials.shinyapps.io/00-setup/
Source: https://github.com/rstudio/ggtutorials/blob/master/tutorials/00-setup/

https://tutorials.shinyapps.io/01-data-basics/
Source: https://github.com/rstudio/ggtutorials/tree/master/tutorials/01-data-basics

https://tutorials.shinyapps.io/03a-data-manip-filter/
Source: https://github.com/rstudio/ggtutorials/tree/master/tutorials/03a-data-manip-filter

https://tutorials.shinyapps.io/03b-data-manip-mutate/
Source: https://github.com/rstudio/ggtutorials/tree/master/tutorials/03b-data-manip-mutate

https://tutorials.shinyapps.io/03c-data-manip-summarise
Source: https://github.com/rstudio/ggtutorials/tree/master/tutorials/03c-data-manip-summarise
