### ISSUE TITLE
Tutorials should not have side padding when hosted within an iframe.

### ISSUE THREAD

**Issue by robbyshaver** [rstudio/tutor#52]
In reviewing the first tutorial presented via RStudio Cloud, the fact that the tutorial is presented in an iframe means it ends up with unwanted horizontal padding, so it doesn't line up with the RStudio Cloud UI elements (it has excessive horizontal padding).

**Comment by jjallaire** [comment]
You could detect showing within any iframe (e.g. http://stackoverflow.com/questions/4353933/show-page-differently-css-if-within-iframe) but that might over-detect (i.e. there could be tutorials which people host in a full width iframe). How about if RStudio Cloud adds a query parameter which you detect and in that case add/remove appropriate styles?

**Comment by robbyshaver** [comment]
That sounds like a good solution - I'll take a crack at it.

**Comment by robbyshaver** [comment]
This approach worked, but on taking a more careful look at what's going on on RStudio Cloud, the issue is that the iframe being used to contain the tutorial is not positioned/sized correctly. No need to adjust tutor padding at this point.
