### ISSUE TITLE
Record and restore the user's current topic

### ISSUE THREAD

**Issue by robbyshaver** [rstudio/tutor#56]
We currently remember and restore the progress a user has made through a tutorial, but we don't record & restore which topic you were last on. It makes picking up where you left off a bit difficult if close and re-open a tutorial.

**Comment by jjallaire** [comment]
We actually have a "client state" mechanism for saving and restoring an arbitrary bag of client state properties:

https://github.com/rstudio/tutor/blob/master/inst/lib/tutor/tutor.js#L1482-L1504

As you can see from the code I originally used this for scroll position but found it janky to actually use. I think that restoring the last topic worked out would be much less janky though. Perhaps we could subscribe to onhashchange and then restore the hash?

**Comment by robbyshaver** [comment]
So to set the state, can I make a call like this one from within
tutorial-format.js? Or does the tutor package need a new method for me to
call?

thiz.$serverRequest("set_client_state", current_client_state, null);

**Comment by jjallaire** [comment]
Not quite, I think the easiest thing is to put a pin in this until I get back from vacation next week and we can go over it realtime. Let's discuss on Monday.

**Comment by robbyshaver** [comment]
Perfect - thanks.

**Comment by jjallaire** [comment]
fixed via PR #59
