### ISSUE TITLE
Scroll instead of jump to newly revealed sub-section

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#58]
We can make progressive reveal a stronger learning tool by scrolling up to the new sub-section instead of jumping to the new sub-section. The jump temporarily breaks the learner's attention because the learner has to figure out how the layout has changed. A quick, automated scroll makes it obvious how the layout changes, which helps the learner maintain attention on the learning task.

This replaces #28 and may prevent the confusion that @mine-cetinkaya-rundel mentions in #51.

**Comment by jjallaire** [comment]
I very much agree with this as I've found the sudden reveal + instant scroll to be disorienting (and I know exactly what's going on!) @robbyshaver Do you think this is something we could implement for the CRAN release?

**Comment by mine-cetinkaya-rundel** [comment]
I agree as well, and agree that it would address my concern from #51.

**Comment by robbyshaver** [comment]
I agree too - I can take a crack at it.
