### ISSUE TITLE
Latex not rendering

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#60]
@dtkaplan mentioned that Latex math is not rendering in tutor documents. I was able to confirm it in the sample below.

````
---
title: "Latex bug"
output: tutor::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
```

## Topic 1

### Sub-section 

$\pi$

````

<img width="1078" alt="screen shot 2017-03-27 at 4 52 10 pm" src="https://cloud.githubusercontent.com/assets/85014/24377634/0776e66e-130e-11e7-9c19-41a186933f16.png">

**Comment by jjallaire** [comment]
Thanks! Just fixed. Note that you will need to make sure that the tutorial html is re-rendered (by deleting the .html file or touching the .Rmd file) in order to see the fix.
