### ISSUE TITLE
teachdown deploy error: No such file or directory

### ISSUE THREAD

**Issue by garrettgman** [rstudio/tutor#62]
@jjallaire I've switched two tutorials over to teachdown, and run into the same bug with each: Each tutorial works locally, but displays this when deployed to shinyapps.io:

<img width="519" alt="screen shot 2017-04-04 at 9 47 40 am" src="https://cloud.githubusercontent.com/assets/85014/24660011/5c27b44a-191c-11e7-9ace-434219337aaf.png">
The tutorials deployed correctly with tutor (and still do if I convert back). Clearing the pre-rendered files and re-rendering hasn't fix it. Do you have any ideas what is happening?

**Comment by jjallaire** [comment]
Thanks for reporting! Should be fixed here: https://github.com/rstudio/tutor/commit/40dcf5b615d1fb8f3167b5fa7986d0a3eba3b3e7

**Comment by garrettgman** [comment]
Thanks! That worked. For instance, https://tutorials.shinyapps.io/01-data-basics/
