### ISSUE TITLE
code in exercises has extra indentation in ace editor

### ISSUE THREAD

**Issue by jjallaire** [rstudio/tutor#63]
All lines other than the first get an extra character of indentation:

<img width="956" alt="screen shot 2017-04-04 at 11 10 10 am" src="https://cloud.githubusercontent.com/assets/104391/24663952/4ff55da2-1927-11e7-8fcb-a98dc71fb7ad.png">

Source code for repro:

    ---
    title: "Tutorial"
    output: tutor::tutorial
    runtime: shiny_prerendered
    ---

    ```{r setup, include=FALSE}
    library(tutor)
    ```

    ```{r plots, exercise=TRUE, exercise.lines = 5}
    summary(cars)
    summary(pressure)
    summary(mtcars)
    ```

**Comment by garrettgman** [comment]
I can verify that this happens.

**Comment by kevinushey** [comment]
I think I've discovered the issue -- there's a typo here:

https://github.com/rstudio/rmarkdown/blob/5f7cd3ca4dbe955fc774139bed6a4b639f4bceb4/R/shiny_prerendered.R#L50

Notice the use of `collapase` instead of `collapse`.

**Comment by jjallaire** [comment]
Wow, that's terrible! (thanks for the fix).
