### ISSUE TITLE
Wrong event-recorder entry for questions when random order is TRUE.

### ISSUE THREAD

**Issue by dtkaplan** [rstudio/tutor#7]
For multiple-choice questions, the `data` argument passed to the function assigned to `tutor.event_recorder` can have the wrong value in the `answers:` field when `random_answer_order = TRUE`. Instead of giving the answer text that corresponds to the selected option in the HTML display, the text is pulled out from the original order given in the `question()` function that set up the possible answers. In other words, randomization is done correctly so far as the display and the evaluation of correctness, but the event recorder doesn't seem to know about the randomization.

**Comment by jjallaire** [comment]
Fixed, thanks!
